### ISSUE TITLE
How to use multibox_focal_loss_layer.cpp/.hpp inSSD?

### ISSUE THREAD

**Issue by RichardMrLu** [chuanqi305/FocalLoss#3]
I have replace caffe.proto with the original one, and put multibox_focal_loss_layer.cpp and multibox_loss_layer.hpp in correct files. finally my train.prototxt modified, but when I train:

Error parsing text-format caffe.NetParameter: 1786:20 :Message type "caffe.LayerParameter" has no field named ''focal_loss_param''.

how to solve this problem? Thanks for your answer!

**Comment by RichardMrLu** [comment]
I have rebulid  caffe, it's ok. but when i trian, it show:
unknown layer type: FocalLoss (know types:...MultiBoxFocalLoss,MultiBoxLoss...)
in train.prototxt, i set the "mbox_loss" type as “MultiBoxFocalLoss”,but it wrong with the "FocalLoss"...why?how to solve this problem, thank you for your answer

**Comment by RichardMrLu** [comment]
oh! I get it! facal_loss_layer.cpp and focal_loss_layer.cu and focal_loss_layer.hpp also shuld added in caffe..

**Comment by foralliance** [comment]
@RichardMrLu 
@chuanqi305 

1. 用作者的caffe.proto替换原SSD中的caffe.proto
2. 将facal_loss_layer.cpp，focal_loss_layer.cu，multibox_focal_loss_layer.cpp放入src/caffe/layers下
3. 将focal_loss_layer.hpp，multibox_focal_loss_layer.hpp放入include/caffe/layers下
4. 修改trian.prototxt文件
5. 编译（make -j8, make pycaffe）

编译都没有问题，可训练时报错：
```
*** Aborted at 1530087655 (unix time) try "date -d @1530087655" if you are using GNU date ***
PC: @     0x7f5bfa349428 gsignal
*** SIGABRT (@0x3e800001704) received by PID 5892 (TID 0x7f5bfd26aac0) from PID 5892; stack trace: ***
    @     0x7f5bfa3494b0 (unknown)
    @     0x7f5bfa349428 gsignal
    @     0x7f5bfa34b02a abort
    @     0x7f5bfa38b7ea (unknown)
    @     0x7f5bfa39613e (unknown)
    @     0x7f5bfa398184 __libc_malloc
    @     0x7f5bfb15be78 operator new()
    @     0x7f5bfb15bf19 operator new[]()
    @     0x7f5bfb6b4b27 google::protobuf::internal::RepeatedPtrFieldBase::Reserve()
    @     0x7f5bfc23877c caffe::LayerParameter::MergeFrom()
    @     0x7f5bfc250017 caffe::InsertSplits()
    @     0x7f5bfc4b09ae caffe::Net<>::Init()
    @     0x7f5bfc4b3b71 caffe::Net<>::Net()
    @     0x7f5bfc2e537a caffe::Solver<>::InitTrainNet()
    @     0x7f5bfc2e6677 caffe::Solver<>::Init()
    @     0x7f5bfc2e6a1a caffe::Solver<>::Solver()
    @     0x7f5bfc2fd683 caffe::Creator_SGDSolver<>()
    @           0x40afb9 train()
    @           0x4077c8 main
    @     0x7f5bfa334830 __libc_start_main
    @           0x408099 _start
    @                0x0 (unknown)

```

这个问题您需要过吗？？？或者我的配置过程有问题吗？？

**Comment by RichardMrLu** [comment]
Sorry, I use PyTorch now...

**Comment by foralliance** [comment]
@RichardMrLu 
使用cmake编译后，问题解决，谢谢！

**Comment by jiachen0212** [comment]
i got loss=nan......

**Comment by ujsyehao** [comment]
@foralliance 你好，需要在caffe.proto里添加MultiBoxFocalLossParameter吗？
