### ISSUE TITLE
error: ‘GetNormalizer’ is not a member of ‘caffe::LossLayer<float>’

### ISSUE THREAD

**Issue by hungsing92** [chuanqi305/FocalLoss#4]
Hi,

When I compile my caffe, this error occured. Could you please upload your LossLayer files?

Thanks,
hungsing

**Comment by Maharshi-Aupera** [comment]
I also met with the same error, for those who also face the same issue can solve that by adding the following lines to your loss_layer.hpp after line number ~31.

```
  Dtype GetNormalizer(
      const LossParameter_NormalizationMode normalization_mode,
      const int outer_num, const int inner_num, const int valid_count);
```
